[book]
authors = ["shnulaa"]
language = "zh-cn"
multilingual = false
src = "src"
title = "shnulaa"

[preprocessor.toc]
command = "mdbook-toc"

[output.html]
site-url = "/mdBook-pages-template"
default-theme = "black"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/shnulaa/mdBook-pages-test"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true
